name = "hugo-geo"
license = "MIT"
licenselink = "https://raw.githubusercontent.com/alexurquhart/hugo-geo/master/LICENSE"
description = "A responsive blog theme made designed for post and tutorial sections"
homepage = "https://alexurquhart.com"
tags = ["blog"]
features = ["blog", "responsive", "sidebar", "social buttons"]
min_version= 0.20

[author]
    name = "Alex Urquhart"
    email = "alexurquhart@gmail.com"
    url = "https://alexurquhart.com"